spring:
    application.name: video-rental-store
    datasource:
      url: jdbc:h2:mem:videoRentalStoreDatabase
      driver-class-name: org.h2.Driver
      username: ${DB_USER:admin}
      password: ${DB_PASS:admin}

    h2.console.enabled: true
    jpa:
      defer-datasource-initialization: true

springdoc.api-docs.path: /api-docs
